steps:
  # --- Step 1: Build Docker Image ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '.'

  # --- Step 2: Push Docker Image to Artifact Registry ---
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

  # --- Step 3: Deploy to Cloud Run (with all optimizations) ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets=DATABASE_URL=_DATABASE_URL:latest'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=300'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

substitutions:
  _SERVICE_NAME: 'voiceassistant-backend'
  _REGION: 'europe-west3'
  _ARTIFACT_REPO_NAME: 'go42tum-backend'
  _DB_SECRET_NAME: '_DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
