steps:
  # --- Step 1: Build Docker image ---
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '.'

  # --- Step 2: Push Docker image to Artifact Registry ---
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

  # --- Step 3: Remove Conflicting Environment Variables ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Remove Conflicting Env Var'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--remove-env-vars=DATABASE_URL'

  # --- Step 4: Deploy to Cloud Run ---
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets=DATABASE_URL=${_DB_SECRET_NAME}:latest'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

substitutions:
  _SERVICE_NAME: 'voiceassistant-backend'
  _REGION: 'europe-west3'
  _ARTIFACT_REPO_NAME: 'cloud-run-source-deploy'
  _DB_SECRET_NAME: 'DATABASE_URL'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
