# When pushing to GitHub, Cloud Build will run these steps in order

steps:
  # --- Step 1: Build Docker image ---
  # Use Google's Docker build tool
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      # Format: REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:COMMIT_SHA
      # Use $SHORT_SHA (short commit ID) as version tag, to track the code version of each deployment
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '.' # Look for Dockerfile in the current directory

  # --- Step 2: Push Docker image to Artifact Registry ---
  # This step will push the image built in the previous step to your private repository
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

  # --- Step 3: Deploy to Cloud Run ---
  # The last step, deploy the image just pushed to the Cloud Run service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    # Use gcloud command to execute deployment
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Inject the database connection string stored in Secret Manager
      # Format: [environment variable name]=[Secret name]:[version]
      - '--set-secrets=DATABASE_URL=${_DB_SECRET_NAME}:latest'

# Define the image to keep after build
# This way you can see all historical versions of the image in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:${SHORT_SHA}'

# Substitute variables, making this configuration file more flexible
# Override these default values in the Cloud Build trigger settings
substitutions:
  _SERVICE_NAME: 'voiceassistant-backend'
  _REGION: 'europe-west3'
  _ARTIFACT_REPO_NAME: 'cloud-run-source-deploy'
  _DB_SECRET_NAME: 'SUPABASE_DB_URL'

# Set the timeout for the build
timeout: '1200s'
